<#
.SYNOPSIS
  Genere les defs d'inventaire du pack : une par mod source, listant ses especes.
.DESCRIPTION
  Croise la table des licences avec le contenu reel de Mod/Defs/<Source>/ et ecrit
  Mod/Defs/_Pack/Sources.xml. La page de reglages "Animal Ark: Contents" s'en sert pour
  afficher la provenance de chaque bete.

  Le fichier est genere, jamais edite a la main : c'est ce qui garantit qu'il decrit le
  contenu present et non le contenu suppose. Les especes sont relevees dans les defs, pas
  recopiees d'une liste.

  -Build filtre sur la colonne Build de la table, pour que chaque variante n'annonce que ses
  propres sources.
.EXAMPLE
  pwsh -File Gen-SourcesDef.ps1 -PackDir ..\AnimalArk
  pwsh -File Gen-SourcesDef.ps1 -PackDir ..\AnimalArk -Build public
#>
param(
    [Parameter(Mandatory=$true)][string]$PackDir,
    [string]$Build,
    [string]$LicenceMap
)

if (-not $LicenceMap) { $LicenceMap = Join-Path $PackDir 'licences-sources.csv' }
$mod = Join-Path $PackDir 'Mod'
$map = Import-Csv $LicenceMap
if ($Build) { $map = @($map | Where-Object Build -eq $Build) }

$lignes = New-Object System.Collections.Generic.List[string]
$lignes.Add('<?xml version="1.0" encoding="utf-8" ?>')
$lignes.Add('<Defs>')
$lignes.Add('')
$lignes.Add('  <!-- GENERATED by scripts/Gen-SourcesDef.ps1. Do not edit by hand: this file')
$lignes.Add('       describes what the pack really holds, read back from the defs. -->')
$lignes.Add('')

$total = 0; $vides = @()
foreach ($r in ($map | Sort-Object DossierDefs)) {
    $dir = Join-Path $mod "Defs\$($r.DossierDefs)"
    if (-not (Test-Path $dir)) { continue }

    # les especes sont les PawnKindDef du dossier, relevees sur place
    $animaux = New-Object System.Collections.Generic.List[string]
    foreach ($f in Get-ChildItem $dir -Filter *.xml -Recurse -File) {
        $t = Get-Content -LiteralPath $f.FullName -Raw
        foreach ($m in [regex]::Matches($t, '(?s)<PawnKindDef[^>]*>((?:(?!</PawnKindDef>).)*?)</PawnKindDef>')) {
            $d = [regex]::Match($m.Value, '<defName>([^<]+)</defName>')
            if ($d.Success -and -not $animaux.Contains($d.Groups[1].Value)) { $animaux.Add($d.Groups[1].Value) }
        }
    }
    if ($animaux.Count -eq 0) { $vides += $r.DossierDefs; continue }
    $total += $animaux.Count

    function Esc($s) { if ($null -eq $s) { '' } else { $s -replace '&','&amp;' -replace '<','&lt;' -replace '>','&gt;' } }

    $lignes.Add('  <Bastyon.AnimalArkSourceDef>')
    $lignes.Add("    <defName>AA_Source_$($r.DossierDefs)</defName>")
    $lignes.Add("    <sourceName>$(Esc $r.Source)</sourceName>")
    $lignes.Add("    <author>$(Esc $r.Auteur)</author>")
    $lignes.Add("    <workshopId>$(Esc $r.WorkshopId)</workshopId>")
    $lignes.Add("    <licence>$(Esc $r.Licence)</licence>")
    $lignes.Add('    <animals>')
    foreach ($a in ($animaux | Sort-Object)) { $lignes.Add("      <li>$a</li>") }
    $lignes.Add('    </animals>')
    $lignes.Add('  </Bastyon.AnimalArkSourceDef>')
    $lignes.Add('')
}

$lignes.Add('</Defs>')

$out = Join-Path $mod 'Defs\_Pack'
New-Item -ItemType Directory -Force -Path $out | Out-Null
$cible = Join-Path $out 'Sources.xml'
Set-Content -LiteralPath $cible -Value $lignes -Encoding UTF8

$n = ($map | Where-Object { Test-Path (Join-Path $mod "Defs\$($_.DossierDefs)") }).Count
Write-Host ("{0} sources, {1} especes -> {2}" -f ($n - $vides.Count), $total, $cible) -ForegroundColor Green
if ($vides) { Write-Host ("  sources sans PawnKindDef, ecartees : {0}" -f ($vides -join ', ')) -ForegroundColor DarkYellow }
